/**
 * gate_rt.h — Stable runtime ABI for gate-codegen'd executables (C11).
 *
 * `gate codegen` emits a design translation unit (<stem>_design.c) that
 * defines every symbol declared below, then compiles it together with
 * gate_rt.c to produce a standalone native binary.
 *
 * ABI split
 * ─────────
 *  gate_rt.c          — stable; ships unchanged with every `gate` build
 *  <stem>_design.c    — emitted fresh for every .gateo file
 */

#ifndef GATE_RT_H
#define GATE_RT_H

#include <stdint.h>

/* ── Design-side ABI (defined in <stem>_design.c) ────────────────────────────
 *
 * These symbols are generated by `gate codegen` and link with gate_rt.c.
 * gate_rt.c uses them to drive argument parsing, evaluation, and printing.
 * ─────────────────────────────────────────────────────────────────────────── */

/** Null-sentinel array of root input-port names (e.g. { "A", "B", NULL }). */
extern const char *const GATE_INPUT_NAMES[];

/** Bit-widths parallel to GATE_INPUT_NAMES; index i gives inputs[i]'s width. */
extern const uint32_t GATE_INPUT_WIDTHS[];

/** Number of root input ports (length of the two arrays above). */
extern const int GATE_INPUT_COUNT;

/** Null-sentinel array of root output-port names. */
extern const char *const GATE_OUTPUT_NAMES[];

/** Bit-widths parallel to GATE_OUTPUT_NAMES. */
extern const uint32_t GATE_OUTPUT_WIDTHS[];

/** Number of root output ports. */
extern const int GATE_OUTPUT_COUNT;

/**
 * Output number format baked in at codegen time; used as the runtime default.
 * Can be overridden at runtime with --output-format.
 *
 *   0 = GATE_FMT_HEX   (default when gate codegen omits --output-format)
 *   1 = GATE_FMT_DEC
 *   2 = GATE_FMT_BIN
 */
extern const int GATE_DEFAULT_OUTPUT_FORMAT;

/**
 * Evaluate the compiled gate network.
 *
 * @param inputs   GATE_INPUT_COUNT values, each already masked to its port
 *                 width by the runtime argument parser.
 * @param outputs  Caller-allocated array of GATE_OUTPUT_COUNT uint64_t.
 *                 Every element is written before design_eval returns.
 */
void design_eval(const uint64_t *inputs, uint64_t *outputs);


/* ── Runtime-side utilities (defined in gate_rt.c) ───────────────────────────
 *
 * Available to design files that include this header (currently none need to,
 * but the declarations are here for completeness and future use).
 * ─────────────────────────────────────────────────────────────────────────── */

/** Output-format constants (mirror the `gate sim --output-format` aliases). */
#define GATE_FMT_HEX 0
#define GATE_FMT_DEC 1
#define GATE_FMT_BIN 2

/**
 * Parse a CLI number string ("42", "0x2a", "0b101010") and mask the result
 * to @p width bits.  Prints a warning to stderr when significant bits are
 * truncated.  Terminates the process with an error message on bad input.
 */
uint64_t rt_parse_number(const char *s, uint32_t width);

/**
 * Print @p val (assumed already width-masked) to stdout in @p fmt.
 * Binary output is zero-padded to exactly @p width digits.
 */
void rt_print_number(uint64_t val, uint32_t width, int fmt);

#endif /* GATE_RT_H */
